create table if not exists call_sessions (
  session_id text primary key,
  customer_id text not null,
  env_key text not null,
  created_at double precision not null,
  updated_at double precision not null,
  ended boolean default false,
  verified_identity boolean default false,
  verification_attempts integer default 0
);

create table if not exists call_turns (
  id bigint generated by default as identity primary key,
  session_id text references call_sessions(session_id),
  ts double precision not null,
  user_transcript text,
  agent_response text,
  tool_calls jsonb
);

create table if not exists configs (
  env_key text primary key,
  base_system_prompt text,
  router_prompt text,
  tool_flags jsonb,
  routing_rules jsonb
);
